### ISSUE TITLE
Graphite-web doesn't show charts (Graphite-web/GrapHouse/ClickHouse stack)

### ISSUE THREAD

**Issue by ipeacocks** [Altinity/clickhouse-graphouse-integration#14]
I've tried this manual twice, everything is working correct except `graphite-web` installation. After installing it graphs can't be showed:

![Image 1](https://i.imgur.com/DDpfPg1.png)
![Image 2](https://i.imgur.com/82hvSrX.png)

Error output (the same on image):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/graphite/webapp/graphite/render/views.py", line 118, in renderView
    data.extend(evaluateTarget(requestContext, targets))
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 15, in evaluateTarget
    prefetchData(requestContext, pathExpressions)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 257, in prefetchData
    for result in STORE.fetch(pathExpressions, startTime, endTime, now, requestContext):
  File "/opt/graphite/webapp/graphite/storage.py", line 190, in fetch
    'fetch for %s' % str(patterns))
  File "/opt/graphite/webapp/graphite/storage.py", line 132, in wait_jobs
    raise Exception(message)
Exception: All requests failed for fetch for ['test.count.test'] (1)

fetch for ['test.count.test']: 'NoneType' object has no attribute 'replace': Traceback (most recent call last):

  File "/opt/graphite/webapp/graphite/node.py", line 30, in fetch
    result = self.reader.fetch(startTime, endTime, now, requestContext)

TypeError: fetch() takes 3 positional arguments but 5 were given


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/graphite/webapp/graphite/worker_pool/pool.py", line 43, in run
    self.result = self.func(*self.args, **self.kwargs)

  File "/opt/graphite/webapp/graphite/finders/utils.py", line 140, in fetch
    now=now, requestContext=requestContext

  File "/opt/graphite/webapp/graphite/node.py", line 33, in fetch
    result = self.reader.fetch(startTime, endTime)

  File "/opt/graphite/webapp/graphite/graphouse.py", line 152, in fetch
    return self.fetcher.fetch(self.path, self.reqkey, start_time, end_time)

  File "/opt/graphite/webapp/graphite/graphouse.py", line 33, in fetch
    paths = [node.path.replace('\'', '\\\'') for node in self.nodes]

  File "/opt/graphite/webapp/graphite/graphouse.py", line 33, in <listcomp>
    paths = [node.path.replace('\'', '\\\'') for node in self.nodes]

AttributeError: 'NoneType' object has no attribute 'replace'

```

**Comment by TH-HA** [comment]
Hello ,
I was facing the same issue. So far it seems to be a compatibility issue between the driver delivered by graphouse and python 3. 
2 possibilities for you : 
   Use python 2.X
   Do the change i've made in this ticket : https://github.com/yandex/graphouse/issues/98 
Regards

**Comment by ipeacocks** [comment]
I've tried graphite-api https://github.com/brutasse/graphite-api and it works just OK.
